# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  Default

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
- task: UiPathInstallPlatform@4
  inputs:
    cliVersion: 'WIN_23.6.8581.19168'
    cliNupkgPath: 'C:\agent1\_work\_tool\nupkg\UiPath.CLI.Windows.23.6.8581.19168.zip'
- task: UiPathPack@4
  inputs:
    versionType: 'AutoVersion'
    projectJsonPath: '$(Build.SourcesDirectory)\project.json'
    outputType: 'Library'
    outputPath: '$(Build.ArtifactStagingDirectory)\Output'